### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by bqio** [dweinstein/node-google-play#102]
Handle polling update error: LoginError: Error=UNKNOWN_ERR
    at C:\Users\admin\Desktop\apkbot\node_modules\gpapi\lib\api.js:132:17
    at tryCatcher (C:\Users\admin\Desktop\apkbot\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\admin\Desktop\apkbot\node_modules\bluebird\js\release\promise.js:514:35)
    at Promise._settlePromise (C:\Users\admin\Desktop\apkbot\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (C:\Users\admin\Desktop\apkbot\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (C:\Users\admin\Desktop\apkbot\node_modules\bluebird\js\release\promise.js:699:18)
    at Promise._fulfill (C:\Users\admin\Desktop\apkbot\node_modules\bluebird\js\release\promise.js:643:18)
    at PromiseArray._resolve (C:\Users\admin\Desktop\apkbot\node_modules\bluebird\js\release\promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (C:\Users\admin\Desktop\apkbot\node_modules\bluebird\js\release\promise_array.js:144:14)
    at PromiseArray._iterate (C:\Users\admin\Desktop\apkbot\node_modules\bluebird\js\release\promise_array.js:114:31)
    at PromiseArray.init [as _init] (C:\Users\admin\Desktop\apkbot\node_modules\bluebird\js\release\promise_array.js:78:10)
    at Promise._settlePromise (C:\Users\admin\Desktop\apkbot\node_modules\bluebird\js\release\promise.js:571:21)
    at Promise._settlePromise0 (C:\Users\admin\Desktop\apkbot\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (C:\Users\admin\Desktop\apkbot\node_modules\bluebird\js\release\promise.js:699:18)
    at Promise._fulfill (C:\Users\admin\Desktop\apkbot\node_modules\bluebird\js\release\promise.js:643:18)
    at Request._callback (C:\Users\admin\Desktop\apkbot\node_modules\bluebird\js\release\nodeback.js:45:21) {
  message: 'Error=UNKNOWN_ERR',
  name: 'LoginError'
}

All data input is correct.

**Comment by dweinstein** [comment]
yeah seems like sometimes the login fails and you have to retry. I don't know any workaround for now other than to retry, sorry.
