### ISSUE TITLE
Login Error - CaptchaRequired

### ISSUE THREAD

**Issue by itsecres-nandant** [dweinstein/node-google-play#117]
`Unhandled rejection LoginError: Error=CaptchaRequired
CaptchaToken=xxxxxxxxxx
CaptchaUrl=https://accounts.google.com/Captcha?ctoken=xxxxxxxxxx&v=2
    at C:\Users\xxxxx\Downloads\Compressed\node-google-play-4.3.2\lib\api.js:132:17
    at tryCatcher (C:\Users\xxxxx\Downloads\Compressed\node-google-play-4.3.2\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\xxxxx\Downloads\Compressed\node-google-play-4.3.2\node_modules\bluebird\js\release\promise.js:509:35)
    at Promise._settlePromise (C:\Users\xxxxx\Downloads\Compressed\node-google-play-4.3.2\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\xxxxx\Downloads\Compressed\node-google-play-4.3.2\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\xxxxx\Downloads\Compressed\node-google-play-4.3.2\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (C:\Users\xxxxx\Downloads\Compressed\node-google-play-4.3.2\node_modules\bluebird\js\release\promise.js:638:18)
    at PromiseArray._resolve (C:\Users\xxxxx\Downloads\Compressed\node-google-play-4.3.2\node_modules\bluebird\js\release\promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (C:\Users\xxxxx\Downloads\Compressed\node-google-play-4.3.2\node_modules\bluebird\js\release\promise_array.js:144:14)
    at PromiseArray._iterate (C:\Users\xxxxx\Downloads\Compressed\node-google-play-4.3.2\node_modules\bluebird\js\release\promise_array.js:114:31)
    at PromiseArray.init [as _init] (C:\Users\xxxxx\Downloads\Compressed\node-google-play-4.3.2\node_modules\bluebird\js\release\promise_array.js:78:10)
    at Promise._settlePromise (C:\Users\xxxxx\Downloads\Compressed\node-google-play-4.3.2\node_modules\bluebird\js\release\promise.js:566:21)
    at Promise._settlePromise0 (C:\Users\xxxxx\Downloads\Compressed\node-google-play-4.3.2\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\xxxxx\Downloads\Compressed\node-google-play-4.3.2\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (C:\Users\xxxxx\Downloads\Compressed\node-google-play-4.3.2\node_modules\bluebird\js\release\promise.js:638:18)
    at Request._callback (C:\Users\xxxxx\Downloads\Compressed\node-google-play-4.3.2\node_modules\bluebird\js\release\nodeback.js:45:21)`

**Comment by itsecres-nandant** [comment]
i have gone through [https://github.com/dweinstein/node-google-play/issues/107](url)
but none of the solutions given there worked for me

**Comment by itsecres-nandant** [comment]
fixed by uninstalling current node version and installing below node version

https://nodejs.org/dist/v8.9.4/node-v8.9.4-x64.msi

once installed above node version, try fresh install from github
