### ISSUE TITLE
DownloadInfo/Download Seems Broken

### ISSUE THREAD

**Issue by stasfrid** [dweinstein/node-google-play#24]
google's api seems to return status code 500 when you do downloadInfo request.

the is error i got
node .\downloadInfo.js
Possibly unhandled RequestError: ↕K↕IError retrieving information from server. [RPC:S-7:AEC-0 RLD2-NXJV-FNI3E]�☺
    at D:\github\node-google-play\lib\api.js:203:17
    at tryCatchApply (D:\github\node-google-play\node_modules\bluebird\js\main\util.js:77:21)
    at Promise$_callSpread [as _callSpread] (D:\github\node-google-play\node_modules\bluebird\js\main\promise.js:649:12)
    at Promise$_callHandler [as _callHandler] (D:\github\node-google-play\node_modules\bluebird\js\main\promise.js:657:18)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (D:\github\node-google-play\node_modules\bluebird\js\main\promise.js:675:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (D:\github\node-google-play\node_modules\bluebird\js\main\promise.js:845:14)
    at Promise$_settlePromises [as _settlePromises] (D:\github\node-google-play\node_modules\bluebird\js\main\promise.js:988:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (D:\github\node-google-play\node_modules\bluebird\js\main\async.js:77:12)
    at Async$consumeFunctionBuffer (D:\github\node-google-play\node_modules\bluebird\js\main\async.js:40:14)
    at process._tickCallback (node.js:419:13)

**Comment by dweinstein** [comment]
works for me. are you using valid credentials?
