### ISSUE TITLE
Unhandled rejection LoginError: Error=NeedsBrowser

### ISSUE THREAD

**Issue by shashi007** [dweinstein/node-google-play#44]
I'm getting this error.
`Unhandled rejection LoginError: Error=NeedsBrowser

ErrorDetail=To access your account, you must sign in on the web. Touch Next to start browser sign-in.
    at node-google-play-master/lib/api.js:154:15
    at tryCatcher (node-google-play-master/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (node-google-play-master/node_modules/bluebird/js/release/promise.js:501:35)
    at Promise._settlePromise (node-google-play-master/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (node-google-play-master/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (node-google-play-master/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (node-google-play-master/node_modules/bluebird/js/release/promise.js:630:18)
    at PromiseArray._resolve (node-google-play-master/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (node-google-play-master/node_modules/bluebird/js/release/promise_array.js:143:14)
    at PromiseArray._iterate (node-google-play-master/node_modules/bluebird/js/release/promise_array.js:113:31)
    at PromiseArray.init [as _init] (node-google-play-master/node_modules/bluebird/js/release/promise_array.js:77:10)
    at Promise._settlePromise (node-google-play-master/node_modules/bluebird/js/release/promise.js:558:21)
    at Promise._settlePromise0 (node-google-play-master/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (node-google-play-master/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (node-google-play-master/node_modules/bluebird/js/release/promise.js:630:18)
    at Request._callback (node-google-play-master/node_modules/bluebird/js/release/nodeback.js:45:21)
`

**Comment by dweinstein** [comment]
Have you tried signing in to resolve it? I don't think this is something the library can resolve for you.

**Comment by shashi007** [comment]
I'm getting all sorts of different errors nvm.
