### ISSUE TITLE
completeDownloadInfo return AssertionError: require downloadUrl

### ISSUE THREAD

**Issue by liranso** [dweinstein/node-google-play#68]
Hi,

Api suddenly stopped working - 

calling gpapi.GooglePlayAPI(gpAccount) to get the API
and then calling api.completeDownloadInfo(packageName,versionCode)
throws an error - **AssertionError: require downloadUrl**

chain of calls - completeDownloadInfo-> getCompleteDownloadInfo-> getDownloadInfo() - result return empty with no data, and then the following row:
        assert(res.downloadUrl, 'require downloadUrl');
causing an error to be thrown

Did anyone else encountered the problem?
Can someone help?

Thanks

**Comment by sharifStrudent** [comment]
Hi
Now Api errors for me too.
Error:
Unhandled rejection TypeError: cannot read property 'low' of null.

please help.

**Comment by honktang** [comment]
same problem

**Comment by Kaggggggga** [comment]
Hi
It seems now the "purchase" api response with a "encodedDeliveryToken" which will be used in "delivery" api to get download url.
However, the "delivery" api requires a "st" parameter, any idea how to get it?

Thanks.

**Comment by archon810** [comment]
Same problem.

**Comment by jacobhub** [comment]
same for me too

**Comment by stas-smedia** [comment]
same here

**Comment by snirad** [comment]
I made a pull request that could fix the issue:
https://github.com/dweinstein/node-google-play/pull/69

you can use the fork untill the fix get pushed to the main repo if you'd like..
https://github.com/snirad/node-google-play

**Comment by stas-smedia** [comment]
@snirad 
i'm getting the following error
`AssertionError: expected appDeliveryData`

**Comment by snirad** [comment]
I tested about 10 different apk's and it seem to be working.

could it be that the apk you are trying to get is not available on play store ?

**Comment by sharifStrudent** [comment]
@snirad
First of all thank you.
After change api to your code, sometimes  downloadUrl request show error: `expected appDeliveryData` but sometimes work correctly!

**Comment by sharifStrudent** [comment]
Complete Error:
```
{ AssertionError: expected appDeliveryData
    at C:\Program Files\nodejs\node_modules\gpapi\lib\api.js:419:9
    at tryCatcher (C:\Program Files\nodejs\node_modules\bluebird\js\release\util
.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\b
luebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Program Files\nodejs\node_modules\bluebird\js\
release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\bluebird\js
\release\promise.js:614:10)
    at Promise._settlePromises (C:\Program Files\nodejs\node_modules\bluebird\js
\release\promise.js:693:18)
    at Promise._fulfill (C:\Program Files\nodejs\node_modules\bluebird\js\releas
e\promise.js:638:18)
    at Promise._resolveCallback (C:\Program Files\nodejs\node_modules\bluebird\j
s\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\b
luebird\js\release\promise.js:524:17)
    at Promise._settlePromise (C:\Program Files\nodejs\node_modules\bluebird\js\
release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\bluebird\js
\release\promise.js:614:10)
    at Promise._settlePromises (C:\Program Files\nodejs\node_modules\bluebird\js
\release\promise.js:693:18)
    at Promise._fulfill (C:\Program Files\nodejs\node_modules\bluebird\js\releas
e\promise.js:638:18)
    at Promise._resolveCallback (C:\Program Files\nodejs\node_modules\bluebird\j
s\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\b
luebird\js\release\promise.js:524:17)
    at Promise._settlePromise (C:\Program Files\nodejs\node_modules\bluebird\js\
release\promise.js:569:18)
  name: 'AssertionError',
  actual: null,
  expected: true,
  operator: '==',
  message: 'expected appDeliveryData',
  generatedMessage: false } 
```

**Comment by stas-smedia** [comment]
@snirad 
hi :)
i've tried package: com.facebook.katana and the version code 70506845

**Comment by imKota** [comment]
@snirad 
i tested your version, and get errors.
```
kota@iMac—Kota ~
➜  gp-download-meta com.symudolcreadigol.prosiectx
AssertionError [ERR_ASSERTION]: expected appDeliveryData
➜  gp-get-sha1 com.symudolcreadigol.prosiectx
AssertionError [ERR_ASSERTION]: expected appDeliveryData
➜  gp-download-info com.symudolcreadigol.prosiectx
AssertionError [ERR_ASSERTION]: expected appDeliveryData
```

**Comment by snirad** [comment]
@imKota  Looks like a problem with the apk in google store,
https://play.google.com/store/apps/details?id=com.symudolcreadigol.prosiectx

**Comment by imKota** [comment]
@snirad Thanks for the quick response!
Tomorrow I'll try to register an account via VPN, and try to download the application. The results will be reported:)

**Comment by serbanica** [comment]
same issue here, @snirad 's PR fixes it

**Comment by Attect** [comment]
@snirad 
I clone your code
it doesn't work 
Unhandled rejection AssertionError: require downloadUrl
    at /home/pi/node_modules/gpapi/lib/api.js:460:9

**Comment by jacobhub** [comment]
I am also getting the 'expected appDeliveryData' error, on some packages:

Download error:
{ AssertionError: expected appDeliveryData
    at /home/ubuntu/gpapi-server/node_modules/gpapi/lib/api.js:419:9
    at tryCatcher (/home/ubuntu/gpapi-server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/gpapi-server/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ubuntu/gpapi-server/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ubuntu/gpapi-server/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ubuntu/gpapi-server/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/ubuntu/gpapi-server/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/home/ubuntu/gpapi-server/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/home/ubuntu/gpapi-server/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/home/ubuntu/gpapi-server/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ubuntu/gpapi-server/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ubuntu/gpapi-server/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/ubuntu/gpapi-server/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/home/ubuntu/gpapi-server/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/home/ubuntu/gpapi-server/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/home/ubuntu/gpapi-server/node_modules/bluebird/js/release/promise.js:569:18)
  name: 'AssertionError',

**Comment by snirad** [comment]
@jacobhub I've seen it happen mostly when application is not supported either by geo or device.

**Comment by snirad** [comment]
Hi,

I changed the flow for getDownloadInfo, looks like if your account trying to download a new apk
 getting downloadInfo from delivery url will fail. however, if you try to get purchase url, and then delivery, it should succeed.

try and see if it works for you.

**Comment by jacobhub** [comment]
now getting this error ( package 'com.facebook.lite' ):

Download error:
{ Error
    at handleErr (/home/ubuntu/gpapiserv/node_modules/gpapi/lib/api.js:248:39)
    at /home/ubuntu/gpapiserv/node_modules/gpapi/lib/api.js:253:28
    at tryCatcher (/home/ubuntu/gpapiserv/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/gpapiserv/node_modules/bluebird/js/release/promise.js:509:35)
    at Promise._settlePromise (/home/ubuntu/gpapiserv/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ubuntu/gpapiserv/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ubuntu/gpapiserv/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/ubuntu/gpapiserv/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/home/ubuntu/gpapiserv/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/home/ubuntu/gpapiserv/node_modules/bluebird/js/release/promise_array.js:144:14)
    at PromiseArray._iterate (/home/ubuntu/gpapiserv/node_modules/bluebird/js/release/promise_array.js:114:31)
    at PromiseArray.init [as _init] (/home/ubuntu/gpapiserv/node_modules/bluebird/js/release/promise_array.js:78:10)
    at Promise._settlePromise (/home/ubuntu/gpapiserv/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/home/ubuntu/gpapiserv/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ubuntu/gpapiserv/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/ubuntu/gpapiserv/node_modules/bluebird/js/release/promise.js:638:18)
  message: 'Google Play purchases are not supported in your country. Unfortunately you will not be able to complete purchases.',
  name: 'RequestError',
  statusCode: 403,

**Comment by snirad** [comment]
@jacobhub doing this using the previous patch worked for you ?
 -it worked for me using a new account. so i think its expected behavior, seeing the message you got

> message: 'Google Play purchases are not supported in your country. Unfortunately you will not be able to complete purchases.',

**Comment by NathanManning** [comment]
@dweinstein, where we at on the pull?

**Comment by dweinstein** [comment]
I don't think the PR maintains API compatibility and I haven't had the time to sort thru it yet.

**Comment by stas-smedia** [comment]
@snirad, any idea why i'm getting  AssertionError [ERR_ASSERTION]: expected appDeliveryData for com.facebook.katana ? if i'm running the details function it works as expected just download is broken

**Comment by stas-smedia** [comment]
is there any progress on this issue?

**Comment by alter-al** [comment]
+1

**Comment by dweinstein** [comment]
try v4.3.2

**Comment by sharifStrudent** [comment]
Thank you @dweinstein but doesn't work!

**Comment by dweinstein** [comment]
Double check that your login information is for a recent device such as nexus on 6.0.1 and that you are getting the android ID as described in the README

**Comment by alter-al** [comment]
@dweinstein thank you, 
I updated google-play-cli to 4.5.0 and gpapi to 4.4.0 and all working awesome

**Comment by sharifStrudent** [comment]
I update gpapi to 4.4.0 and use GSFID of Android 6.1 but when use `api.deliveryData(pkg, vc).` get the error 

> expected appDeliveryData

**Comment by sharifStrudent** [comment]
I fixed it by using `completeDownloadInfo` instead of `deliveryData`.
Thank You @dweinstein .
