### ISSUE TITLE
Error retrieving information from server. [RH-02]

### ISSUE THREAD

**Issue by bd9142** [dweinstein/node-google-play#81]
Hi, info about error:

gpapi:  4.3.2

code:

var playapi = require('gpapi').GooglePlayAPI({
	"username": "xx@gmail.com",
	"password": "xxx",
	"androidId": "Exxxxx",
	"apiUserAgent": "Android-Finsky/8.7.10-all (api=3,versionCode=80871000,sdk=23,device=mp1s3gss,hardware=mp1s3gss,product=mp1s3gss_global_com,platformVersionRelease=6.0,model=LG-H542,buildId=MRA58K,isWideScreen=0,supportedAbis=armeabi-v7a;armeabi)",
	"downloadUserAgent": "AndroidDownloadManager/6.0 (Linux; U; Android 6.0; LG-H542 Build/MRA58K)",
});

playapi.details("com.mobinavel.KeepTheBall", function (err, res) {
    console.log(err ? err : res);
  });

Error:
Error retrieving information from server. [RH-02]

Details:

Error
    at handleErr (c:\Users\mobinavel\Documents\downloadTest\node_modules\gpapi\lib\api.js:237:31)
    at c:\Users\mobinavel\Documents\downloadTest\node_modules\gpapi\lib\api.js:242:18
    at tryCatcher (c:\Users\mobinavel\Documents\downloadTest\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (c:\Users\mobinavel\Documents\downloadTest\node_modules\bluebird\js\release\promise.js:509:35)
    at Promise._settlePromise (c:\Users\mobinavel\Documents\downloadTest\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (c:\Users\mobinavel\Documents\downloadTest\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (c:\Users\mobinavel\Documents\downloadTest\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (c:\Users\mobinavel\Documents\downloadTest\node_modules\bluebird\js\release\promise.js:638:18)
    at PromiseArray._resolve (c:\Users\mobinavel\Documents\downloadTest\node_modules\bluebird\js\release\promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (c:\Users\mobinavel\Documents\downloadTest\node_modules\bluebird\js\release\promise_array.js:144:14)
    at PromiseArray._iterate (c:\Users\mobinavel\Documents\downloadTest\node_modules\bluebird\js\release\promise_array.js:114:31)
    at PromiseArray.init [as _init] (c:\Users\mobinavel\Documents\downloadTest\node_modules\bluebird\js\release\promise_array.js:78:10)
    at Promise._settlePromise (c:\Users\mobinavel\Documents\downloadTest\node_modules\bluebird\js\release\promise.js:566:21)
    at Promise._settlePromise0 (c:\Users\mobinavel\Documents\downloadTest\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (c:\Users\mobinavel\Documents\downloadTest\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (c:\Users\mobinavel\Documents\downloadTest\node_modules\bluebird\js\release\promise.js:638:18)"

**Comment by dweinstein** [comment]
I'm not able to reproduce this, check the ANDROID_ID value you're using and confirm how you're getting it. https://github.com/dweinstein/node-google-play#id-and-user-agent

**Comment by bd9142** [comment]
I used  "device id app " that is referenced in docs. If u want to try my android_id , i can give it. By the way, i cannot understand RH-02 error. do u know anything about it ?

**Comment by bd9142** [comment]
probably wrong id set. i think  it will be good instead of andoid_id in document as gsf_id.

**Comment by dweinstein** [comment]
> ANDROID_ID - the ID for the device for Google. This is the GSF ID not the id from dialing *#*#8255#*#*. You can get the gsf id e.g., using the device id app

related to #80
